import { printSectionTitle, runCommandOrThrow } from "./script-helpers.mjs";

/**
 * This script builds the two documentation outputs that are served from static files:
 * the API reference generated by TypeDoc and the tutorial site generated by VitePress.
 */

printSectionTitle("Building the API reference");
runCommandOrThrow("npm", ["run", "docs:api"]);

printSectionTitle("Building the tutorial site");
runCommandOrThrow("npm", ["run", "docs:site:build"]);

console.log("\nDocumentation build complete.");
