import { spawnSync } from "node:child_process";

/**
 * This script builds the two documentation outputs that are served from static files:
 * the API reference generated by TypeDoc and the tutorial site generated by VitePress.
 */

function runCommandOrThrow(commandName, commandArguments) {
  const completedCommandResult = spawnSync(commandName, commandArguments, {
    cwd: process.cwd(),
    stdio: "inherit",
    shell: process.platform === "win32"
  });

  if (completedCommandResult.status !== 0) {
    throw new Error(
      `The command ${commandName} ${commandArguments.join(" ")} failed with exit code ${completedCommandResult.status}.`
    );
  }
}

runCommandOrThrow("npm", ["run", "docs:api"]);
runCommandOrThrow("npm", ["run", "docs:site:build"]);

